{% set name = "pnpm" %}
{% set version = "7.27.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: dbbea184933ca04e029f200355c949cd86b3e647d12831410886f65bee386584

build:
  number: 0

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - yarn
  run:
    - nodejs

test:
  commands:
    - pnpm --help

about:
  home: https://github.com/pnpm/pnpm
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: 📦🚀 Fast, disk space efficient package manager

extra:
  recipe-maintainers:
    - xhochy
    - pavelzw
