{% set name = "pnpm" %}
{% set version = "7.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 32406510ce38b68a1c57e5e79d7ed5385697aebd21236bd6f58046d4310f724f

build:
  number: 0

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - yarn
  run:
    - nodejs

test:
  commands:
    - pnpm --help

about:
  home: https://github.com/pnpm/pnpm
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: 📦🚀 Fast, disk space efficient package manager

extra:
  recipe-maintainers:
    - xhochy
